/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        background: "#111318",
        surface: "#111318",
        "surface-dim": "#111318",
        "surface-bright": "#37393e",
        "surface-container-lowest": "#0c0e12",
        "surface-container-low": "#1a1c20",
        "surface-container": "#1e2024",
        "surface-container-high": "#282a2e",
        "surface-container-highest": "#333539",
        "on-surface": "#e2e2e8",
        "on-surface-variant": "#c2c6d6",
        "inverse-surface": "#e2e2e8",
        "inverse-on-surface": "#2f3035",
        outline: "#8c909f",
        "outline-variant": "#424754",
        "surface-tint": "#adc6ff",
        primary: "#adc6ff",
        "on-primary": "#002e6a",
        "primary-container": "#4d8eff",
        "on-primary-container": "#00285d",
        "inverse-primary": "#005ac2",
        secondary: "#c4c6d3",
        "on-secondary": "#2d303a",
        "secondary-container": "#444651",
        "on-secondary-container": "#b3b4c1",
        tertiary: "#bcc7de",
        "on-tertiary": "#263143",
        "tertiary-container": "#8691a7",
        "on-tertiary-container": "#1f2a3c",
        "tertiary-fixed-dim": "#bcc7de",
        error: "#ffb4ab",
        onError: "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#d8e2ff",
        "primary-fixed-dim": "#adc6ff",
        "on-primary-fixed": "#001a42",
        "on-primary-fixed-variant": "#004395",
        "secondary-fixed": "#e0e2ef",
        "secondary-fixed-dim": "#c4c6d3",
        "on-secondary-fixed": "#181b25",
        "on-secondary-fixed-variant": "#444651",
        "tertiary-fixed": "#d8e3fb",
        "on-tertiary-fixed": "#111c2d",
        "on-tertiary-fixed-variant": "#3c475a",
        "surface-variant": "#333539",
      },
      borderRadius: {
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-padding": "24px",
        gutter: "16px",
        "sidebar-width": "260px",
        "component-gap": "8px",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "ui-monospace", "monospace"],
        "data-mono": ["JetBrains Mono", "ui-monospace", "monospace"],
        "code-sm": ["JetBrains Mono", "ui-monospace", "monospace"],
        "display-lg": ["Inter", "system-ui", "sans-serif"],
        "headline-md": ["Inter", "system-ui", "sans-serif"],
        "title-sm": ["Inter", "system-ui", "sans-serif"],
        "body-md": ["Inter", "system-ui", "sans-serif"],
        "body-sm": ["Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "title-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "data-mono": ["13px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "code-sm": ["11px", { lineHeight: "14px", fontWeight: "400" }],
      },
      boxShadow: {
        "glow-primary": "inset 2px 0 0 0 #adc6ff",
        "glow-error": "0 0 8px rgba(255,180,171,0.5)",
      },
    },
  },
  plugins: [],
};
